apiVersion: v1
kind: Service
metadata:
  name: petclinic-service
  namespace: spc
spec:
  type: LoadBalancer
  selector:
    app: spring-petclinic
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
